### ISSUE TITLE
The plugin uses version of package, not Flutter version 🤦 

### ISSUE THREAD

**Issue by romanr** [NiklasLehnfeld/flutter-version-number-action#11]
The plugin should use Flutter version, keypath "environment">"flutter":

```yaml
version: 1.0.0 # version of project, not Flutter

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '3.19.2'
```
