### ISSUE TITLE
BUG: grep doesn't take only the 1st available value of `version`

### ISSUE THREAD

**Issue by TheFe91** [NiklasLehnfeld/flutter-version-number-action#9]
As per title, consider to have a pubspec.yaml like this:

```yaml
name: aName
version: 1.0.1

# configs...

dependencies:
  # some deps

dev_dependencies:
  # some deps
  version: ^1.0.0
```

This will result in an output of `1.0.1_^1.0.0` which is not a valid tag.
